In [3]:
import numpy as np
from thinkdsp import CosSignal, SumSignal
from thinkdsp import Wave

In [4]:
PI2 = np.pi * 2

## Synthesize

In [26]:
amps = np.array([0.6, 0.25, 0.1, 0.05])
fs = [100, 200, 300, 400]
framerate = 11025

In [27]:
ts=np.linspace(0, 1,num=framerate, endpoint=False)

In [28]:
def synthesize2(amps, fs, ts):
    args=np.outer(ts, fs)
    M = np.cos(PI2*args)
    ys=np.dot(M, amps)
    return ys

In [29]:
ys =synthesize2(amps, fs, ts)

In [30]:
wave = Wave(ys, ts, framerate)
wave.apodize()
wave.make_audio()

## DCT-IV

In [31]:
N=len(ys)
N

11025

In [32]:
np.arange(N)

array([    0,     1,     2, ..., 11022, 11023, 11024])

In [33]:
ts= (0.5 + np.arange(N)) / N
ts

array([4.53514739e-05, 1.36054422e-04, 2.26757370e-04, ...,
       9.99773243e-01, 9.99863946e-01, 9.99954649e-01])

In [34]:
fs=(0.5 + np.arange(N))/2
fs

array([2.50000e-01, 7.50000e-01, 1.25000e+00, ..., 5.51125e+03,
       5.51175e+03, 5.51225e+03])

In [35]:
args = np.outer(ts, fs)
M = np.cos(PI2 * args)

In [36]:
amps = M@ys / 2
amps

array([ 0.23516962,  0.29450585,  0.17585912, ...,  0.24999978,
       -0.25000015,  0.24999995])

In [37]:
def dct_iv(ys):
    N=len(ys)
    ts= (0.5 + np.arange(N)) / N
    fs= (0.5 + np.arange(N)) / 2
    args =np.outer(ts, fs)
    M=np.cos(PI2*args)
    amps=M@ys/2
    return amps


In [38]:
amps = np.array([0.6, 0.25, 0.1, 0.05])
N = 4.0
ts = (0.5 + np.arange(N)) / N
fs = (0.5 + np.arange(N)) / 2
ys = synthesize2(amps, fs, ts)

amps2 = dct_iv(ys)
np.max(np.abs(amps - amps2))

8.326672684688674e-17